# Generated by Django 5.0.4 on 2024-04-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_historicalperformance_deleted_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='delivery_date',
            new_name='expected_delivery_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='actual_delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
